(()=>{function e(s){var n=r[s];if(void 0!==n)return n.exports;var i=r[s]={exports:{}};return t[s](i,i.exports,e),i.exports}var t={2672:e=>{e.exports={meta:{type:"suggestion",docs:{description:"aligns attributes in the metadata",category:"Stylistic Issues"},schema:[{type:"integer",minimum:1,default:2}],messages:{spaceMetadata:"The metadata is not spaced"},fixable:"code"},create:e=>{const t=e.options[0]||2,r=e.getSourceCode(),s=r.getAllComments();let n=!1,i=!1,a=[],o={},l={}
;for(const e of s.filter(e=>"Line"===e.type))i||(n&&"==/UserScript=="===e.value.trim()?(l=e.loc.end,i=!0):n||"==UserScript=="!==e.value.trim()?n&&e.value.trim().startsWith("@")&&a.push({key:e.value.trim().slice(1).split(/\s/)[0],space:/^\S*(\s+)/.exec(e.value.trim().slice(1))[1].length,line:e.loc.start.line,comment:e}):(o=e.loc.start,n=!0));if(0===Object.keys(l).length&&(l=r.getLocFromIndex(r.getText().length)),0===a.length)return{};const c=Math.max(...a.map(e=>e.key.length))+t
;return(a.map(e=>e.space).sort()[0]<t||a.map(e=>e.key.length+e.space).find(e=>e!==c))&&e.report({loc:{start:o,end:l},messageId:"spaceMetadata",fix:function(e){const t=[];for(const s of a)if(s.key.length+s.space!==c){const n=/^(.*?@\S*)/.exec(r.getLines()[s.line-1])[1].length;t.push(e.replaceTextRange([r.getIndexFromLoc({line:s.line,column:n}),r.getIndexFromLoc({line:s.line,column:n+s.space})]," ".repeat(c-s.key.length)))}return t}}),{}}}},8039:e=>{e.exports={meta:{type:"suggestion",docs:{
description:"ensure userscripts end with .user.js",category:"Best Practices"},schema:[{enum:["always","never"]}],messages:{filenameExtension:"Rename '{{ oldFilename }}' to '{{ newFilename }}'"}},create:e=>{const t=e.getFilename();return"<input>"===t||"<text>"===t?{}:{Program(){(!t.endsWith(".user.js")&&(!e.options[0]||"always"===e.options[0])||t.endsWith(".user.js")&&"never"===e.options[0])&&e.report({loc:{column:0,line:1},messageId:"filenameExtension",data:{
newFilename:t.replace("always"===e.options[0]?/.js$/:/.user.js$/,"always"===e.options[0]?".user.js":".js"),oldFilename:t}})}}}}},70:(e,t,r)=>{
const s=r(2598),n=["addElement","addStyle","addValueChangeListener","cookie","deleteValue","download","getResourceText","getResourceURL","getTab","getTabs","getValue","info","listValues","log","notification","openInTab","registerMenuCommand","removeValueChangeListener","saveTab","setClipboard","setValue","unregisterMenuCommand","xmlhttpRequest"].map(e=>"GM_"+e),i=["addElement","addStyle","addValueChangeListener","cookie","deleteValue","download","getResourceText","getResourceUrl","getTab","getTabs","getValue","info","listValues","log","notification","openInTab","registerMenuCommand","removeValueChangeListener","saveTab","setClipboard","setValue","unregisterMenuCommand","xmlHttpRequest"].map(e=>"GM."+e),a=new Set([...n,...i,"none","unsafeWindow","window.close","window.focus","window.onurlchange"])
;e.exports=s("grant",!1,({attrVal:e,context:t})=>{const r=e.val;a.has(r)||t.report({loc:{start:{line:e.loc.start.line,column:0},end:e.loc.end},messageId:"grantHasInvalidArgument",data:{argument:r}})},{grantHasInvalidArgument:"'{{ argument }}' is not a valid @grant argument"})},8754:(e,t,r)=>{
const s=r(2598),n=new Set(["antifeature","author","connect","contributor","contributors","copyright","defaulticon","description","developer","downloadURL","exclude","grant","history","homepage","homepageURL","icon","icon64","icon64URL","iconURL","include","license","match","name","namespace","nocompat","noframes","require","resource","run-at","source","supportURL","updateURL","version","website"].map(e=>"@"+e)),i=["name","description","antifeature"].map(e=>new RegExp(`^@${e}(:\\S+)?$`))
;e.exports=s("headers",!1,({attrVal:e,context:t})=>{const r=t.options[0],s=new Set((r&&r.allowed||[]).map(e=>"@"+e));for(const r of e){const e="@"+r.key;n.has(e)||s.has(e)||i.some(t=>t.test(e))||t.report({loc:{start:{line:r.loc.start.line,column:0},end:r.loc.end},messageId:"invalidHeader",data:{header:e}})}},{invalidHeader:"'{{ header }}' is not a valid userscript header"},!1,/./,!0,[{type:"object",properties:{allowed:{type:"array"}},additionalProperties:!1}])},1763:e=>{e.exports={meta:{
type:"suggestion",docs:{description:"ensure userscripts have valid metadata",category:"Possible Errors"},messages:{metadataRequired:"Add metadata to the userscript",moveMetadataToTop:"Move the metadata to the top of the file",noClosingMetadata:"Closing metadata comment not found",noCodeBetween:"Code found between in metadata",attributeNotStartsWithAtTheRate:"Attributes should begin with @"},schema:[{type:"object",properties:{top:{enum:["required","optional"],default:"required"}},
additionalProperties:!1}]},create:e=>{const t=e.getSourceCode(),r=t.getAllComments(),s=t.lines;let n=!1,i=!1;for(const[t,r]of s.entries()){if(i)continue;const s={start:{line:t+1,column:0},end:{line:t+1,column:r.length}};n&&!r.trim().startsWith("//")&&r.trim()?e.report({loc:s,messageId:"noCodeBetween"
}):n&&r.trim().startsWith("//")&&"==/UserScript=="===r.trim().slice(2).trim()?i=!0:!n&&r.trim().startsWith("//")&&"==UserScript=="===r.trim().slice(2).trim()?n=!0:n&&!r.trim().slice(2).trim().startsWith("@")&&r.trim().slice(2).trim()&&e.report({loc:s,messageId:"attributeNotStartsWithAtTheRate"})}return{Program(t){0!==r.length&&r.find(e=>"==UserScript=="===e.value.trim()&&"Line"===e.type)?(r.find(e=>"==/UserScript=="===e.value.trim()&&"Line"===e.type)||e.report({
loc:r.find(e=>"==UserScript=="===e.value.trim()&&"Line"===e.type).loc,messageId:"noClosingMetadata"}),e.options[0]&&e.options[0].top&&"required"!==e.options[0].top||"==UserScript=="===r[0].value.trim()&&1===r[0].loc.start.line||e.report({loc:r.find(e=>"==UserScript=="===e.value.trim()&&"Line"===e.type).loc,messageId:"moveMetadataToTop"})):e.report({node:t,messageId:"metadataRequired"})}}}}},4350:e=>{e.exports={meta:{type:"suggestion",docs:{
description:"ensure atributes are prefixed by one space",category:"Possible Errors"},messages:{attributeNotPrefixedBySpace:"Attributes should be prefixed by one space"},schema:[]},create:e=>{const t=e.getSourceCode().lines;let r=!1,s=!1;for(const[n,i]of t.entries()){if(s)continue;const t=i.trim()
;r&&t.startsWith("//")&&"==/UserScript=="===t.slice(2).trim()?s=!0:!r&&t.startsWith("//")&&"==UserScript=="===t.slice(2).trim()?r=!0:r&&t.slice(2).trim().startsWith("@")&&t.startsWith("//")&&(!t.startsWith("// ")||t.startsWith("//  "))&&e.report({loc:{start:{line:n+1,column:0},end:{line:n+1,column:i.length}},messageId:"attributeNotPrefixedBySpace"})}return{}}}},230:(e,t,r)=>{const s=r(2598);e.exports=s("description",!0,({attrVal:e,context:t})=>{let r=[]
;for(let s of e)r.includes(s.key)?t.report({loc:s.loc,messageId:"multipleDescriptions"}):r.push(s.key)},{multipleDescriptions:"Include only one description for each language"},!1,/^description(:\S+)?$/,!0)},8295:(e,t,r)=>{const s=r(2598),n=/^name(:\S+)?$/;e.exports=s("name",!0,({attrVal:e,context:t,metadata:r})=>{let s=[];for(let r of e)s.includes(r.key)?t.report({loc:r.loc,messageId:"multipleNames"}):s.push(r.key);const i=Object.values(r)
;if(i.find((e,t)=>0!==t&&n.test(e[0]?e[0].key:e.key)&&!n.test(i[t-1][0]?i[t-1][0].key:i[t-1].key))){const r=t.getSourceCode(),s=r.getAllComments(),n=s.find(e=>"==/UserScript=="===e.value.trim()&&"Line"===e.type);t.report({loc:{start:s.find(e=>"==UserScript=="===e.value.trim()&&"Line"===e.type).loc.start,end:n?n.loc.end:{line:r.lines.length,column:0}},messageId:"nameAtBeginning",fix:function(r){let s=[];for(let n of e){Array.isArray(n)||(n=[n])
;for(let e of n)s.push(r.removeRange(e.comment.range.map((r,s)=>0===s?r-t.getSourceCode().lines[e.loc.start.line-1].split("//")[0].length-1:r)))}return s.push(r.insertTextAfterRange(t.getSourceCode().getAllComments().find(e=>"==UserScript=="===e.value.trim()).range,e.sort((e,t)=>"name"===e.key?-1:"name"===t.key?1:0).map(e=>`\n${t.getSourceCode().lines[e.loc.start.line-1].split("//")[0]}//${e.comment.value}`).join(""))),s}})}},{multipleNames:"Include only one name for each language",
nameAtBeginning:"The names should be at the beginning of the metadata"},!0,n,!0)},3880:(e,t,r)=>{const s=r(2598);e.exports=s("version",!0,({attrVal:e,index:t,context:r})=>{t>0&&r.report({loc:e.loc,messageId:"multipleVersions"}),/^([\dA-Za-z-]+)(\.[\dA-Za-z-]+)*\s*$/.test(e.val)||r.report({loc:{start:{line:e.loc.start.line,column:/^(\s*\/\/\s*)/.exec(r.getSourceCode().lines[e.comment.loc.start.line])[1].length-1},end:e.loc.end},messageId:"invalidVersion"})},{
multipleVersions:"Include only one version",invalidVersion:"Invalid version"})},2215:(e,t,r)=>{const s=r(2598),n=["downloadURL","updateURL"];e.exports=s(n,!1,({attrVal:e,metadata:t,context:r,keyName:s})=>{const i=n.find(e=>e!==s);t[i]||r.report({loc:e.loc,messageId:"missingAttribute",data:{attribute:i},fix:function(t){return t.insertTextAfterRange(e.comment.range,"\n"+r.getSourceCode().lines[e.comment.loc.start.line-1].replace(/^(\s*\/\/\s*@)\S*/,"$1"+i))}})},{
missingAttribute:"Didn't find attribute '{{ attribute }}' in the metadata"},!0)},1933:(e,t,r)=>{const s=r(2598),n=["homepage","homepageURL"];e.exports=s(n,!1,({attrVal:e,metadata:t,context:r,keyName:s})=>{const i=n.find(e=>e!==s);t[i]||r.report({loc:e.loc,messageId:"missingAttribute",data:{attribute:i},fix:function(t){return t.insertTextAfterRange(e.comment.range,"\n"+r.getSourceCode().lines[e.comment.loc.start.line-1].replace(/^(\s*\/\/\s*@)\S*/,"$1"+i))}})},{
missingAttribute:"Didn't find attribute '{{ attribute }}' in the metadata"},!0)},2598:e=>{e.exports=function(e,t,r=!1,s={},n=!1,i=new RegExp("^("+("string"==typeof e?e:e.join("|"))+")$"),a=!1,o){return"string"==typeof e&&(e=[e]),{meta:{type:"suggestion",docs:{description:`${t?"require "+(r?"and validate ":""):"validate "}${e.join(" and ")} in the metadata for userscripts`,category:"Best Practices"},schema:t?[{enum:["required","optional"],default:"required"}]:o||void 0,messages:{
missingAttribute:`Didn't find attribute '${e}' in the metadata`,...s},fixable:n?"code":void 0},create:e=>{const s=e.getSourceCode().getAllComments();let n=!1,o=!1,l=!1,c={};for(const e of s.filter(e=>"Line"===e.type))if(!l)if(n&&"==/UserScript=="===e.value.trim())l=!0;else if(n||"==UserScript=="!==e.value.trim()){if(n&&e.value.trim().startsWith("@")){const t=e.value.trim().slice(1).split(/[ \t]/)[0],r={val:e.value.trim().slice(1).split(/[ \t]/).slice(1).join(" ").trim(),loc:e.loc,comment:e,key:t
};if(c[t]){Array.isArray(c[t])||(c[t]=[c[t]]),c[t].push(r);continue}c[t]=r}}else n=!0,o=!0;const d=Object.keys(c);if(!t||!o||e.options[0]&&"required"!==e.options[0]||d.find(e=>i.test(e))){if(r&&d.find(e=>i.test(e)))if(a){const t=[];for(const e in d)i.test(d[e])&&t.push(+e);const s=t.map(e=>c[d[e]]).reduce((e,t)=>Array.isArray(t)?[...e,...t]:[...e,t],[]);r({attrVal:s,index:[...s.keys()],indexMatch:t.reduce((e,t)=>Array.isArray(c[d[t]])?[...e,...c[d[t]].map(()=>d)]:[...e,t],[]),metadata:c,
context:e,keyName:t.map(e=>d[e])})}else for(const t in d)if(i.test(d[t]))if(Array.isArray(c[d[t]]))for(const[s,n]of c[d[t]].entries())r({attrVal:n,index:s,indexMatch:t,metadata:c,context:e,keyName:d[t]});else r({attrVal:c[d[t]],index:0,indexMatch:t,metadata:c,context:e,keyName:d[t]})}else e.report({loc:s.find(e=>"==UserScript=="===e.value.trim()&&"Line"===e.type).loc,messageId:"missingAttribute"});return{}}}}}},r={};e.n=t=>{var r=t&&t.__esModule?()=>t.default:()=>t;return e.d(r,{a:r}),r},
e.d=(t,r)=>{for(var s in r)e.o(r,s)&&!e.o(t,s)&&Object.defineProperty(t,s,{enumerable:!0,get:r[s]})},e.o=(e,t)=>({}.hasOwnProperty.call(e,t)),(()=>{"use strict";var t=e(8039),r=e.n(t),s=e(70),n=e.n(s),i=e(8754),a=e.n(i),o=e(1763),l=e.n(o),c=e(8295),d=e.n(c),u=e(230),m=e.n(u),p=e(3880),g=e.n(p),f=e(4350),h=e.n(f),y=e(1933),v=e.n(y),x=e(2215),b=e.n(x),S=e(2672),w=e.n(S);const A={rules:{"userscripts/filename-user":r(),"userscripts/no-invalid-grant":n(),"userscripts/no-invalid-headers":a(),
"userscripts/no-invalid-metadata":l(),"userscripts/require-name":d(),"userscripts/require-description":m(),"userscripts/require-version":g(),"userscripts/require-attribute-space-prefix":h(),"userscripts/use-homepage-and-url":v(),"userscripts/use-download-and-update-url":b(),"userscripts/align-attributes":w()}};(()=>{let e="/";self.onmessage=t=>{const r=t.data;if("base_uri"==r.method){const t=r.value;if(!t)throw new Error("missing base URI");e=t}else if("lint"==r.method){
let{config:t,text:s,id:n,options:i}=r;if(!n)throw new Error("missing id");if(!s)throw new Error("missing text");if(!t)throw new Error("missing linter config");i=i||{};try{self.eslint||self.importScripts(e+"vendor/eslint/eslint.js");const r=((e,t,r)=>{const s=self.eslint,n={problem:"error",layout:1,suggestion:1},i=new s.Linter;if(i.defineRules(A.rules),t.extends&&t.extends.includes("eslint:recommended")){const e=t.rules=t.rules||{};i.getRules().forEach((function(t,r){if(!t||void 0!==e[r])return
;const s=t.meta;if(!s)return;const i=s.docs;if(!i||!i.recommended)return;let a;const o=[(s.type?n[s.type]:null)||1],l=s.schema;if(l){const e={};(Array.isArray(l)?l:[l]).forEach(t=>{if("object"!=t.type)return;const r=t.properties;r&&Object.entries(r).forEach(([t,r])=>{const s=r.default;void 0!==s&&!1!==s&&(e[t]=r.default,a=!0)})}),a&&o.push(e)}e[r]=o}))}return i.verify(e,t,r)})(s,t,i);self.postMessage({results:r,id:n})}catch(e){self.postMessage({error:e,id:n})}}}})()})()})();